Test: add testing for mqtt client client
device-automation-bus/dab-tools pull request #14
Opened 2022-12-22 10:00 UTC by andrewqiamzn

2022-12-22 10:05 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            const publishResponse = await (await testClient).publish(topics.DAB_MESSAGES);
had to `await testClient` in every test as `testClient` wasn't awaited in the `before each`. If there is a cleaner way, please let me know!

2022-12-23 11:21 UTC, giotar requested changes

2022-12-23 11:21 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            });
A shorter syntax would be `.handle(inputTopic, mockHandler)`

2022-12-23 11:21 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            await (await testClient).end();
A way to test that the handlers have been removed is to send a message after `end` is called and verify that it's not received by the handler. Something like:
```
asyncMqttClientOnCallBacks["message"](inputTopic, "a message");
expect (mockHandler).haveBeenCalledWith("a message");
await testClient.end();
mockHandler.mockClear();
asyncMqttClientOnCallBacks["message"](inputTopic, "another message");
expect (mockHandler).not.haveBeenCalled();
```

2022-12-23 11:21 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            expect(mockHandler).toBeCalled();
Nit: better to check that the handler has been called with the right params

2022-12-23 11:21 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            await requestResponse;
Add an assertion on the response to validate it is the expected one

2022-12-23 11:21 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +        it("should not publish if the handler failed to receive a request topic", async () => {
This test is a bit unclear. My understanding is that it should be "should not publish a response if there is no handler associated to the topic". Is it right? In which case it's better to set an explicit topic in the message `topic: "someOtherTopic"` so that it's clearer

2022-12-23 11:21 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            asyncMqttClientOnCallBacks["connect"]();
This is replicated in all tests, because all APIs (except `connect()`) need to be called after `connect()` has been called. Consider to add a `describe("after connect")` block and put this statement in the `beforeEach`.  You can leave only the tests of `connect()` outside this describe block. 

Also, we would need a test for the case when these APIs are called before calling `connect()`. I imagine they will fail? throw an error? These tests could go in another describe block "before connect"

2022-12-28 09:31 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            const publishResponse = await (await testClient).publish(topics.DAB_MESSAGES);
No, if I do `testClient = await connect(mockUri)`, it would never resolve as the i would never call the the `on` call back here. This is why I couldn't await it. 
![image](https://user-images.githubusercontent.com/116744710/209790514-b264df60-0d9b-4346-adc1-82ed62e69362.png)

2022-12-28 09:31 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            const publishResponse = await (await testClient).publish(topics.DAB_MESSAGES);
I also tried doing this, but because i get a promise, typescript raises an error.
![image](https://user-images.githubusercontent.com/116744710/209790562-b80af42a-ad9d-4b4a-ac24-ec8d594e1c18.png)

2022-12-28 09:32 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +    connect: EventCallback;
Good point, fixed in the next commit.

2022-12-28 09:35 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +    describe("connect", () => {
Maybe this wasn't clear, this is testing the exported function `connect` that creates and returns a `Client` object (screenshot below). The actual client object doesn't have any `connect` methods.

![image](https://user-images.githubusercontent.com/116744710/209791001-7ad6d556-deda-4447-a551-f6a827a92a27.png)

2022-12-28 09:38 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            });
Ah nice, fixed in the next commit!

2022-12-28 09:39 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            asyncMqttClientOnCallBacks["connect"]();
Thanks for spotting this. I don't need it and have updated the test to check for an error instead.

2022-12-28 09:59 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            await (await testClient).end();
Got it! We're basically checking the before and after effects of removing the listener! Thanks

2022-12-28 10:46 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            await requestResponse;
This is just a `Promise<void>`, so it might not be that useful to assert this. I'll update the variable name to `requestPromise` to clarify that it needed to be awaited.

2022-12-28 10:59 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +        it("should not publish if the handler failed to receive a request topic", async () => {
This test is testing the code flow for when there is no request topic (screenshot). I can make it clearer by extracting it to a variable `emptyRequestTopic = ""`

2022-12-28 11:52 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            asyncMqttClientOnCallBacks["connect"]();
I've updated accordingly for the first point, thanks! For the second point, the only way the function `connect` throws an error is if the `onError` callback is called, and subsequently rejects with an error.

![image](https://user-images.githubusercontent.com/116744710/209807864-ed457f4e-ea88-4676-9b0a-3740669884c1.png)

2022-12-28 11:58 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            asyncMqttClientOnCallBacks["connect"]();
I've updated my test to check for this error here

2023-01-06 14:21 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            const publishResponse = await (await testClient).publish(topics.DAB_MESSAGES);
You could probably do 
```
const connectPromise = connect(mockuri);
asyncMqttclientOnCallbacks["connect"]();
testclient = await connectPromise;
```

2023-01-06 14:49 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            asyncMqttClientOnCallBacks["connect"]();
Yes, that's correct. 

As I have written in another comment, I would only add to this beforeEach 
```
testClient = await connectPromise
```
so to not have it in each test

2023-01-06 16:52 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +            asyncMqttClientOnCallBacks["connect"]();
Neat! I've updated :)

2023-01-11 11:18 UTC, giotar approved these changes

2023-01-11 11:18 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +                    await testClient
Leftover `await`?

2023-01-11 11:44 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +                    await testClient
Ah! Thanks for spotting :)

2023-01-11 16:11 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +jest.setTimeout(30000);
About 5.5 seconds

Looks like one of the tests (line 157) takes 5 seconds which is the one using the fake timer.


![Screenshot 2023-01-11 at 16 09 45](https://user-images.githubusercontent.com/116744710/211856969-517bc5cb-0549-4b81-b9f1-d77309297fce.png)

2023-01-11 16:23 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +jest.setTimeout(30000);
I think it's using real timers as the MQTT timeout is also supposed to be 5 seconds. You can test that by increasing timeout to 30 seconds and seeing what happens.

2023-01-11 16:44 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/__tests__/client.test.ts
> +jest.setTimeout(30000);
Yeah you're right. It does increase to 30 seconds. I tried using `jest.runAllTimers()` [here to try to counteract this](https://github.com/device-automation-bus/dab-tools/pull/14/files/77bc0141bff9d637fdca4ef6b08ea36bd760d701#diff-f7261cd1b3f876661c3ccb98c70ee595b2da761435a0130e3f6bf38bae145eafR161)

2023-01-16 12:04 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/client.ts
> -import { setTimeout, clearTimeout } from "timers";
The problem was that nodejs timers were imported, which jest couldn't mock, hence jest's fake timers didn't work.

2023-01-16 13:16 UTC, amzn-stenlaan approved these changes

2023-01-16 13:18 UTC, merged