Convert ADB bridge to TypeScript
device-automation-bus/dab-tools pull request #4
Opened 2022-09-23 14:34 UTC by amzn-stenlaan

This revealed a bunch of type issues and spec compliance issues. Noteworthy changes:
- In mqtt_client/client.ts, terminate the MQTT client in connect if it
  fails to initialize. Otherwise, the bridge would not terminate if the
  client could not connect to a broker.
- In dab_adb_bridge.ts, in deviceInfo, return a status code
- In dab_adb_bridge.ts in launchApp, simplify logic around the
  parameters to only consider strings and string arrays. Technically,
  the spec says we should only consider string arrays, however existing
  logic needs to be able to determine whether to append a string to the
  final parameter or to pass standalone parameters. This append case is
  handled by passing a single string as parameters.
- In dab/dab_client, pass "appId" instead of "app" to app telemetry
  operations. In dab_device_interface, use "appId" instead of "app".
  This is the format expected by the specification
- In dab_adb_bridge.ts, rename uptimeSeconds to uptimeSince in
  deviceInfo response. This is the field expected by the DAB spec.
- In dab_adb_bridge.ts, rename response fields to comply with spec in
  listApps

See individual commit messages for more detailed changes.

2022-09-23 16:23 UTC, fvbrennan commented
I haven't started a proper review yet, but I pulled the code and attempted to run it with Node v16.16.0. I ran into a few immediate problems I'll have to debug:
1) On the bridge side, my device started being interrogated for device properties, NIC type, but failed getting MAC from IP indicating the device's IP is invalid? I'll pull down the current ADB bridge and see if I get the same results there with the TV I'm testing
2) When I launch the same test, it fails immediately reporting:
/Users/fbrennan/WebstormProjects/dab-adb-bridge-ts/adapters/dab-adb-bridge/src/dist/lib/mqtt_client/index.js:53
                await subscription.end();
                ^
ReferenceError: Cannot access 'subscription' before initialization

2022-09-23 17:00 UTC, fvbrennan requested changes
I haven't gone through the code changes yet, but the ADB Bridge no longer works for me, at least with the Sony Bravia ATV I just tested while the ADB Bridge code in main branch still functions as expected. I'm just marking this as request changes to prevent an accidental merge until we can triage what is causing the failures

2022-09-26 13:31 UTC, amzn-stenlaan commented
>On the bridge side, my device started being interrogated for device properties, NIC type, but failed getting MAC from IP indicating the device's IP is invalid? I'll pull down the current ADB bridge and see if I get the same results there with the TV I'm testing

Interesting, I tested with an Android TV emulator which seems so skip that whole code path (it probably emulates a serial adb connection). Will dig out a physical device and try debugging with that.

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/dab_scenario.test.ts
> +        while(rebooting) {
do we want to try this forever? should we have a max number of attempts?

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/dab_scenario.test.ts
> +        let key_response;
nit: indentation issue? this is still under the for loop, right?

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/dab_scenario.test.ts
> +        await sleep(1000);
why do we need a sleep here?

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/dab_scenario.test.ts
> +        catch (e) {}
are we sure we don't want a failure to stop to fail the test? if stop isn't working correctly wouldn't we want to know here?

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/lib/dab/dab_constants.ts
> +export enum ApplicationState {
What's the difference between ApplicationState and AppStatus? Can they be merged? Can we be consistent between our use of App and Application?

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_interface.ts
> +        this.client.handle(topics.APPLICATIONS_LIST_TOPIC, this.listApps);
why do we not need to await these anymore? The mqtt client handle method is still async

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/lib/mqtt_client/client.ts
> +        response = JSON.parse(msg.toString());
why `msg.toString()` instead of `JSON.stringify`?

2022-10-03 10:58 UTC, egillingham commented on adapters/dab-adb-bridge/src/lib/mqtt_client/client.ts
> +    const defaultOptions = { qos: 2, retain: false };
can this be a class constant?

2022-10-05 13:22 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/mqtt_client/client.ts
> +        response = JSON.parse(msg.toString());
`msg` is a `Buffer`, we don't care about its internal fields that `JSON.stringify` would expose.

For reference
```
> const buf = Buffer.alloc(16);
undefined
> JSON.stringify(buf);
'{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}'
> buf.toString();
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

2022-10-05 13:23 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/dab/dab_constants.ts
> +export enum ApplicationState {
`AppStatus` is a adb concept while `ApplicationState` is a DAB concept. Fair point about consistency though, will change everything to use `Application`.

Will also add a JSDoc to the enums.

2022-10-05 13:25 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/dab_scenario.test.ts
> +        catch (e) {}
Fair, will remove the catch.

2022-10-05 13:25 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/dab_scenario.test.ts
> +        await sleep(1000);
No idea, it's always been here. Seems safe to remove though.

2022-10-05 13:28 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/dab_scenario.test.ts
> +import {DabKey} from "./lib/adb/adb_keymap";
Yeah formatting is all busted, I wanted to keep this PR to just TypeScript changes though and add Prettier+ESLint later

2022-10-05 15:12 UTC, egillingham commented on adapters/dab-adb-bridge/src/lib/dab/dab_constants.ts
> +export enum ApplicationState {
Could we name it `AndroidApplicationStatus` or something like that to make it clear in the name itself?

2022-10-07 11:53 UTC, giotar requested changes

2022-10-07 11:53 UTC, giotar commented on adapters/dab-adb-bridge/src/package.json
> +    "typescript": "^4.8.2"
I would take the opportunity to also add ESLint and Prettier, or at least Prettier. It's better to do it now when files are added rather than later

2022-10-07 11:53 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/client.ts
> +    public async request(topic: string, payload = {}, options: IClientPublishOptions & { timeoutMs?: number } = {
Doesn't `payload` have a type?

2022-10-07 11:53 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/mqtt_client/index.ts
> +    private mqtt!: Client;
Where is `this.mqtt` defined?

2022-10-07 11:53 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_interface.ts
> +export abstract class DabDeviceInterface {
Can you rename this class? Having an class called "Interface" is not great

2022-10-07 11:53 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_interface.ts
> +    private client!: MqttClient;
Is the "!" needed because `client` is only created in `init` and can be undefined? I'd rather throw an explicit error in case `init` has not been called, rather than assume that it is always called. But if it requires too many changes never mind

2022-10-10 09:01 UTC, amzn-stenlaan commented
Regarding Francis's comments, I've tested on a real device and found the same issues. One was that when refactoring `AdbCommands.VALID_IP_REGEX` to a class variable, I forgot to add a `!` at the beginning of the check in adb_commands.ts connect method.

The other issue was with MQTT broker callbacks being invoked before a subscription to that topic is available (not sure how that's possible but it is). Fixed by not `await`ing in mqtt_client/index.ts subscribeOnce, instead `.then()`-ing the subscription promise to ensure that it's cancelled only if it exists.

2022-10-10 09:11 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/package.json
> +    "typescript": "^4.8.2"
I'd prefer to do it in a separate PR to keep the diff smaller and easier to reviewer in this PR (see https://github.com/device-automation-bus/dab-tools/pull/4#discussion_r987923532)

2022-10-10 09:12 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/mqtt_client/client.ts
> +    public async request(topic: string, payload = {}, options: IClientPublishOptions & { timeoutMs?: number } = {
Ah TypeScript didn't complain because it used `{}` for the type from the default value. Changed to `unknown`.

2022-10-10 09:13 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/mqtt_client/index.ts
> +    private mqtt!: Client;
In `init`. It can't be created in the constructor because `connect` which initializes the client is `async`

2022-10-10 09:17 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_interface.ts
> +export abstract class DabDeviceInterface {
Renamed to `DabDeviceBase`, also removed check from constructor because abstract classes can't be initialized anyway.

2022-10-13 14:19 UTC, giotar approved these changes

2022-10-17 09:42 UTC, egillingham approved these changes

2022-10-17 09:53 UTC, merged