Feature: format with prettier
device-automation-bus/dab-tools pull request #6
Opened 2022-10-31 17:31 UTC by andrewqiamzn

2022-11-01 15:03 UTC, giotar requested changes
The prettified code looks good, but you need to add the `.prettierrc` file, add the prettier dependency in `package.json` and possibly also a couple of NPM scripts to check and fix the format

2022-11-01 18:44 UTC, giotar approved these changes

2022-11-01 18:44 UTC, giotar commented on adapters/dab-adb-bridge/src/package.json
> +    "eslint-plugin-prettier": "^3.4.0",
I don't think you need these two ESLint plugins, do you?

2022-11-02 10:07 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/package.json
> +    "eslint-plugin-prettier": "^3.4.0",
good spot! I copied and pasted from our ConciergeClient package.json, but it seems like we don't need the `eslint-plugin-prettier`

2022-11-02 10:12 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/package.json
> +    "eslint-plugin-prettier": "^3.4.0",
fixed!

2022-11-02 10:32 UTC, merged