Feature: add eslint configuration and update ts version
device-automation-bus/dab-tools pull request #8
Opened 2022-11-02 15:26 UTC by andrewqiamzn

2022-11-02 16:38 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "no-unused-vars": "off",
These are the same eslint rules as `ConciergeClient` and `TRExClient`. Overtime, we can think about turning them to warnings and then to errors, as we improve our codebase.

2022-11-02 17:18 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "no-unused-vars": "off",
When we eventually add github workflows, we can prevent merging if a cr fails eslint checks

2022-11-03 10:04 UTC, giotar requested changes

2022-11-03 10:04 UTC, giotar commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/camelcase": "off",
Do we need this?

2022-11-03 10:04 UTC, giotar commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-non-null-assertion": "off",
Do we need this?

2022-11-03 11:00 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/package.json
> +    "typescript": "3.8",
![Screenshot 2022-11-03 at 10 59 04](https://user-images.githubusercontent.com/116744710/199704114-cab6c6b5-3515-4999-b3c3-86ec9d3e7065.png)
I received this warning when linting with ^4.8.2 ! Also our package.json in our other repos stick with 3.8. However, this is just a warning and works fine, so i'm happy to change it back.

2022-11-03 11:05 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/tsconfig.json
> +    "target": "es2020",
Ah, I believe this was incompatible with an earlier version of typescript. Now that I've updated the typescript version to a new one, this works fine!

2022-11-03 11:09 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-empty-function": "off",
Very good point. After linting this codebase, we get 49 errors. Do we want to manage these errors first, before turning on more rules? Be good to get your thoughts on this, as these rules are currently just the exact same ones as we use in our other repos.
![Screenshot 2022-11-03 at 11 07 19](https://user-images.githubusercontent.com/116744710/199705687-f995d64b-c1d6-435f-af7b-4ca2fffc56be.png)

2022-11-03 11:10 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +    overrides: [
Very true, we don't have any js files 🥳

2022-11-03 11:13 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/camelcase": "off",
Nope! Will update in my next commit

2022-11-03 11:15 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-non-null-assertion": "off",
Turning this off, gives us a few extra warnings in our codebase. The the case for this rule is this -> 
`TypeScript's ! non-null assertion operator asserts to the type system that an expression is non-nullable, as in not null or undefined. Using assertions to tell the type system new information is often a sign that code is not fully type-safe. It's generally better to structure program logic so that TypeScript understands when values may be nullable.`

2022-11-03 11:16 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-non-null-assertion": "off",
Which i think is useful, so I agree in that it shouldn't be `off`

2022-11-04 16:08 UTC, giotar commented on adapters/dab-adb-bridge/src/package.json
> +    "typescript": "3.8",
We probably just need to upgrade typescript-eslint to the latest version: https://github.com/typescript-eslint/typescript-eslint#supported-typescript-version

2022-11-04 16:11 UTC, giotar commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-empty-function": "off",
We should try to fix them, or as many as possible. It shouldn't take much, but if you find that some of them require more work you can leave them for another PR

2022-11-04 16:17 UTC, giotar commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-non-null-assertion": "off",
So remove it, if possible

2022-11-04 17:13 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-non-null-assertion": "off",
Done :)

2022-11-04 17:14 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-empty-function": "off",
I've removed the "off" rules so now they appear as warnings.

2022-11-04 17:15 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        "@typescript-eslint/no-empty-function": "off",
Okay, so should we timebox ourselves to fix all the errors before we merge this branch? Or should we create a new branch to fix these errors?

2022-11-07 10:41 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/package.json
> +    "typescript": "3.8",
Done

2022-11-08 16:59 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/adb/adb_commands.ts
> +        //todo: fix "Promise executor functions should not be async" eslint error
Bit unsure how to resolve this eslint error. There's multiple nested promises that need to be awaited within an async function, but eslint is not a fan of `async promise executors`.
![Screenshot 2022-11-08 at 16 59 00](https://user-images.githubusercontent.com/116744710/200628097-81e22ae2-7f2c-4044-a6e8-97074cbb4eb6.png)

2022-11-08 17:02 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/util.ts
> +        // todo: remove ts-ignore
removing ts-ignore triggers typing errors. Do we need to update the type of logger? 
![Screenshot 2022-11-08 at 17 02 10](https://user-images.githubusercontent.com/116744710/200628801-f88fee6c-cf5a-43ce-9e32-b18f9b4901b2.png)

2022-11-08 17:06 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/client.ts
> -    private static readonly DEFAULT_PUBLISH_OPTIONS = { qos: 2, retain: false };
The rule `"@typescript-eslint/member-ordering": "error"` requires me to place methods before properties. I haven't seen this pattern in our other codebases. Should we proceed with this? This was a "two-way door" decision, so I decided to proceed, but i can easily revert back if this is not the desired pattern

2022-11-08 17:06 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/mqtt_client/error.ts
> +    private readonly status: number;
"@typescript-eslint/member-ordering": "error"

2022-11-08 17:07 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/adb/adb_commands.ts
> -    private static readonly VALID_IP_REGEX =
`"@typescript-eslint/member-ordering": "error"`

2022-11-08 17:07 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/dab/dab_client.ts
> -    private client: MqttClient;
`"@typescript-eslint/member-ordering": "error"`

2022-11-08 17:08 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_base.ts
> -    private readonly telemetry: Telemetry;
`"@typescript-eslint/member-ordering": "error"`

2022-11-08 17:08 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/dab_adb_bridge.ts
> -    private readonly adb: AdbCommands;
`"@typescript-eslint/member-ordering": "error"`

2022-11-08 19:11 UTC, giotar requested changes

2022-11-08 19:11 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_base.ts
> +        console.log(data);
Why this added console.log (here and below)?

2022-11-08 19:11 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/util.ts
> +        // todo: remove ts-ignore
No, let's leave it like that with the ignore

2022-11-08 19:11 UTC, giotar commented on adapters/dab-adb-bridge/src/tsconfig.json
> -    "useUnknownInCatchVariables": false,
Can you restore this?

2022-11-11 17:11 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_base.ts
> +        console.log(data);
This was added in order to get round the eslint error `@typescript-eslint/no-unused-vars`
<img width="1360" alt="Screenshot 2022-11-11 at 17 10 22" src="https://user-images.githubusercontent.com/116744710/201393118-4888038d-3c3c-4c9a-be8e-34bf0a95e3de.png">

2022-11-11 17:12 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_base.ts
> +        console.log(data);
I assume `data` was to be used in future use cases, when we do eventually implement the function, hence why i left it.

2022-11-11 17:13 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/tsconfig.json
> -    "useUnknownInCatchVariables": false,
will do in my next commit!

2022-11-11 17:41 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/dab/dab_device_base.ts
> +        console.log(data);
fixed with _data!

2022-11-15 18:04 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/adb/adb_commands.ts
> +        //todo: fix "Promise executor functions should not be async" eslint error
It should be fixed but for now let's add the ignore
```
// eslint-disable-next-line no-async-promise-executor
```

2022-11-15 18:10 UTC, giotar commented on adapters/dab-adb-bridge/src/lib/adb/adb_commands.ts
> +    public async getDeviceUptimeSeconds(): Promise<number> {
The movements of methods in this file makes it impossible to understand what the changes are. 
Only for this file I would keep the existing ordering and add the ignore

2022-11-15 18:15 UTC, giotar requested changes

2022-11-15 18:15 UTC, giotar commented on adapters/dab-adb-bridge/src/.eslintrc.js
> +        tsconfigRootDir: __dirname,
I don't think you need this?

2022-11-15 18:15 UTC, giotar commented on adapters/dab-adb-bridge/src/tsconfig.eslint.json
> +}
I am not sure why you need this file. I think we should use the original tsconfig.json

2022-11-15 18:15 UTC, giotar commented on adapters/dab-adb-bridge/src/package.json
> +    "eslint-plugin-jsdoc": "^33",
You need to upgrade this to ^34 in order to be compatible with ESlint 8

```
npm WARN eslint-plugin-jsdoc@33.3.0 requires a peer of eslint@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```

2022-11-16 10:33 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/package.json
> +    "eslint-plugin-jsdoc": "^33",
interesting. I'll manually update it. `npm install package@latest --force` didn't seem to do it here!

2022-11-16 10:55 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/tsconfig.eslint.json
> +}
Before adding this, I would receive a parsing error `Parsing error: Cannot read file '/users/andrewqi/code/dab-tools/adapters/dab-adb-bridge/tsconfig.json'.eslint` in my `.eslintrc.js`. According to this, eslint throws an error if you attempt to lint a file outside of your project (?) due to  performance reasons.

![image](https://user-images.githubusercontent.com/116744710/202161263-b716c236-da2f-413f-ad22-262d888301f6.png)

2022-11-16 11:09 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/adb/adb_commands.ts
> +    public async getDeviceUptimeSeconds(): Promise<number> {
Ah maybe i could have made my commits more micro. That way it would be better to read?

2022-11-16 11:10 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/adb/adb_commands.ts
> +    public async getDeviceUptimeSeconds(): Promise<number> {
I will:
1. Revert the changes in adb_commands.ts
2. See if there's a better way to show changes. If there's not i can leave it as it is and use eslint ignore

2022-11-16 11:26 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/adb/adb_commands.ts
> +    public async getDeviceUptimeSeconds(): Promise<number> {
updated! :)

2022-11-17 12:12 UTC, giotar commented on adapters/dab-adb-bridge/src/tsconfig.eslint.json
> +}
You shouldn't receive that error now. In any case you can ignore files in ESLint without adding another tsconfig file. You can add a pattern to `ignorePattern` in the esslintrc file, or add it to .eslintignore file.

2022-11-17 19:32 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/tsconfig.eslint.json
> +}
Done :)

2022-11-17 20:12 UTC, andrewqiamzn reviewed
Will squash these commits before merging to clean the commit history.

2022-11-18 15:33 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/.eslintignore
> +dist/
Can't we use `ignorePatterns` in `eslintrc` for this?

2022-11-18 15:33 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/package.json
> +    "package": "^1.0.1",
What's this used for?

2022-11-18 15:33 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/util.ts
> +            // eslint-disable-next-line
We should probably just disable the rule that prohibits `ts-ignore`, otherwise all places with `ts-ignore` will have these double-comments

2022-11-21 10:56 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/package.json
> +    "package": "^1.0.1",
What `npm` used to use to read `package.json`. It's been deprecated, so I'll remove it!
https://github.com/vesln/package

2022-11-21 10:57 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/.eslintignore
> +dist/
Good question. We can - I'll update

2022-11-21 10:58 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/util.ts
> +            // eslint-disable-next-line
So we're unlikley to use `ts-ignore` again. This was a very specific use case and we don't want to encourage coding malpractices by disabling the rule

2022-11-21 16:24 UTC, amzn-stenlaan commented on adapters/dab-adb-bridge/src/lib/util.ts
> +            // eslint-disable-next-line
But the fact that you already have to type out `ts-ignore` should be enough to prevent this from happening. The double-comment to disable both tsc and ESLint is just tedious.

2022-11-21 16:24 UTC, amzn-stenlaan approved these changes

2022-11-21 18:09 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/util.ts
> +            // eslint-disable-next-line
That's a good point. If we find ourselves adding `ts-ignore` and then eslint disable excessively in the future, we should probably disable the rule. That being said, if that happens then maybe we should think about fixing the ts issue itself and removing the need for `ts-ignore` completely.

2022-11-21 18:12 UTC, andrewqiamzn commented on adapters/dab-adb-bridge/src/lib/util.ts
> +            // eslint-disable-next-line
I still think the pros of enforcing this rule outweigh the cons of this extra line

2022-11-22 15:30 UTC, merged